print("Please fill in the blanks below: ")
print("___(name)___'s favorite subject in school is ___(subject)___")
name = input("What is name? ")
subject = input("What is subjec? ")   
print("%s's favorite subject in school is %s." % (name, subject))